kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30007  # This is the node port which is mapped to our localhost
        hostPort: 30007  # This is our localhost port 
  - role: worker
    extraPortMappings:
      - containerPort: 30007
        hostPort: 30008
  - role: worker
# kind: Cluster
# apiVersion: kind.x-k8s.io/v1alpha4
# nodes:
#   - role: control-plane
#     extraPortMappings:
#       - containerPort: 30007 # Port inside the container
#         hostPort: 30007 # Port on the host
#   - role: worker
#   - role: worker
